# Site wide configuration

title: Chip's Github Blog
locale: en_US
description: My playground for trying new things.
logo: site-logo.png
search: true
url: http://chipoglesby.github.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Chip Oglesby
  avatar: bio-photo.jpg
  email: chip@creativesparkcolumbia.com
  disqus-shortname:
  twitter: chipoglesby
  facebook: #username
  github: chipoglesby
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: chipoglesby
  instagram: #username
  flickr: chipoglesby
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: chipoglesby
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
