# Site wide configuration

title: Chip's Github Blog
locale: en_US
description: My playground for trying new things.
logo: site-logo.png
search: true
url: http://chipoglesby.github.io

# Site owner
owner:
  name: Chip Oglesby
  avatar: bio-photo.jpg
  email: chip@creativesparkcolumbia.com
  disqus-shortname:
  twitter: chipoglesby
  facebook: #username
  github: chipoglesby
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: chipoglesby
  instagram: #username
  flickr: chipoglesby
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: chipoglesby
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
